server:
  name: go-sql-modular-sample
  port: 8080

sql:
  driver: postgres
  data_source_name: postgres://xkjofgbu:MKmT3B0PPIZ6pr057wEHFUMvtad5nXex@satao.db.elephantsql.com/xkjofgbu

log:
  level: info
  fields: app,service,username
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: request
  response: response
  size: size
  masks: username
  constants:
    app: "backoffice"
    service: back-office
  map:
    username: username

status:
  not_found: 0
  duplicate_key: 0
  success: 1
  version_error: 2
  validation_error: 4
  error: 4

action:
  create: create
  update: update
  patch: patch
  delete: delete

client:
  endpoint:
    url: "http://localhost:8080/users"
    timeout: 1s
  log:
    log: true
    size: size
    status: status
    request: request
    response: response
